### ISSUE TITLE
New line with indent

### ISSUE THREAD

**Issue by stocarul** [stocarul/dotvim#2]
@ssergiuss: is this the only way:  https://github.com/ssergiuss/dotvim/commit/5599208af165aced27cf2a1cb34368785868aa7a ?

**Comment by ssergiuss** [comment]
@stocarul: No, it is not. My preferred way is using the CR expand config of the DelimitMate plugin. You could find the changes I've made here https://github.com/ssergiuss/dotvim/commit/814035e1d1c2a7685de44073c89364b4e3c3bd5f.
Note that this feature requires that 'backspace' is either set to 2 or has 'ell' and 'start' as part of its value.

Vim :metal:!
